### ISSUE TITLE
How do I install a mod list

### ISSUE THREAD

**Issue by sealvessel** [Spoons/rmm#4]
Do I just paste the links in? Could you provide more detailed instructions, like we just paste steam workshop links?

**Comment by HonzoNebro** [comment]
Just scroll down in the list and read the USAGE section

**Comment by Spoons** [comment]
Unfortunately, there is no way to directly import a steam workshop mod list. Mod list in the documentation refers to mod lists generated by rmm itself. I will consider adding workshop mod lists to rmm because that does seem like it could be a useful feature. For now, just go ahead and install each mod individually.
